[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  SECRETS_SCAN_OMIT_PATHS = "dist/**,*.md,src/services/**,src/config/**,firebase-****.mjs,src/utils/**,*.example,package-lock.json"
  SECRETS_SCAN_OMIT_KEYS = "VITE_FIREBASE_API_KEY,VITE_FIREBASE_AUTH_DOMAIN,VITE_FIREBASE_PROJECT_ID,VITE_FIREBASE_STORAGE_BUCKET,VITE_FIREBASE_MESSAGING_SENDER_ID,VITE_FIREBASE_APP_ID,VITE_FIREBASE_MEASUREMENT_ID,VITE_OPENROUTER_API_KEY,VITE_OPENROUTER_MOONSHOT_API_KEY,VITE_OPENROUTER_QWEN_API_KEY,VITE_SITE_NAME,VITE_SITE_URL,VITE_YOCO_MODE,VITE_YOCO_PUBLIC_KEY,VITE_YOCO_SECRET_KEY"

[functions]
  directory = "netlify/functions"
  external_node_modules = ["node-fetch"]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**/*"]

[functions.openrouter-service]
  included_files = ["netlify/functions/**/*"]

[functions.payment-service]
  included_files = ["netlify/functions/**/*"]

[functions.yoco]
  included_files = ["netlify/functions/**/*"]
  
[functions.yoco.environment]
  YOCO_SECRET_KEY = "${YOCO_SECRET_KEY}"
  VITE_YOCO_PUBLIC_KEY = "${VITE_YOCO_PUBLIC_KEY}"

[dev]
  command = "npm run dev"
  port = 8080
  targetPort = 5173
  publish = "dist"
  framework = "#custom"

# API redirects first
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Direct Yoco function access
[[redirects]]
  from = "/.netlify/functions/yoco/*"
  to = "/.netlify/functions/yoco/:splat"
  status = 200

# SPA fallback last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# CORS headers
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Max-Age = "86400"
    Cross-Origin-Resource-Policy = "cross-origin"
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
    Cross-Origin-Embedder-Policy = "unsafe-none"
